version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    healthcheck:
      test: ["pg_isready", "-U", "postgres"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
  modmail:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=modmail
    restart: always
    links:
      - postgres 
    depends_on:
      - postgres
    ports:
      # 5555: for prisma studio 
      - "5555:5555"
      # 50: for modmail's built-in webserver
      - "3001:80"
    volumes:
      - /app
