version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /data:/var/lib/postgresql/data/pgdata
  server:
    build: .
    ports:
      - "3001:80"
    links:
      - postgres 
    volumes:
      - /app:/opt/app
