version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
  modmail:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=modmail
    ports:
      - "3001:80"
    links:
      - postgres 
    volumes:
      - /app
