version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
  modmail:
    build: .
    restart: always
    ports:
      - "3001:80"
    links:
      - postgres 
    volumes:
      - /app
    networks:
      - attachments
  modmail-attachments:
    image: ghcr.io/fg-devs/attachment-service:latest
    restart: always
    environment:
      - GRPC_PORT=59001
      - HTTP_PORT=8420
      - CDN_URI=https://cdn.modmail.pewdiemc.com/
      - RUST_LOG=info,tower_http=debug%       
    ports:
      - 59001:59001
      - 8420:8420
    volumes:
      - modmail-attachment-files:/app/files
    networks:
      - attachments

networks:
  attachments:
